export const DATE_QUESTIONS: { q: string; category: string }[] = [
  { q: "What was the first thing you noticed about me?", category: "First Impressions" },
  { q: "If we could relive one day together, which one would you pick?", category: "Memories" },
  { q: "What's a small thing I do that always makes you smile?", category: "Little Things" },
  { q: "Describe our love in three words.", category: "Feelings" },
  { q: "Where would you take me on a perfect surprise date?", category: "Dreams" },
  { q: "What's your favorite version of me?", category: "Feelings" },
  { q: "Which song reminds you of us?", category: "Memories" },
  { q: "What's a habit of mine you secretly find adorable?", category: "Little Things" },
  { q: "If we could travel anywhere together tomorrow, where?", category: "Dreams" },
  { q: "What's the most romantic thing I've ever done for you?", category: "Memories" },
  { q: "What do you want more of in our relationship?", category: "Deep" },
  { q: "How do you know when I'm truly happy?", category: "Little Things" },
  { q: "What's your favorite memory of us laughing?", category: "Memories" },
  { q: "If you had to describe my smile, what would you say?", category: "Feelings" },
  { q: "What's one thing you'd love us to try together?", category: "Dreams" },
  { q: "Which of my quirks do you find most endearing?", category: "Little Things" },
  { q: "What's a moment when you felt closest to me?", category: "Deep" },
  { q: "What do you daydream about us doing someday?", category: "Dreams" },
  { q: "What's your favorite thing about our mornings/nights together?", category: "Little Things" },
  { q: "If I made you a playlist, what mood would it capture?", category: "Feelings" },
  { q: "What's the softest thing you'd never say out loud, until now?", category: "Deep" },
  { q: "Which memory of us do you replay the most?", category: "Memories" },
  { q: "How would you describe the way I love you?", category: "Deep" },
  { q: "What's a tiny gesture from me that means the world?", category: "Little Things" },
  { q: "If we wrote a book about us, what would the first line be?", category: "Dreams" },
  { q: "What's your favorite place we've been together?", category: "Memories" },
  { q: "When do you feel most yourself around me?", category: "Deep" },
  { q: "What's a fantasy about us you've never shared?", category: "Deep" },
  { q: "What's the best compliment I've ever given you?", category: "Memories" },
  { q: "If our love had a scent, what would it smell like?", category: "Feelings" },
  { q: "What's one thing you want me to know today?", category: "Feelings" },
  { q: "Describe a perfect lazy Sunday with me.", category: "Dreams" },
  { q: "What's something you love about how we argue and make up?", category: "Deep" },
  { q: "What's my most kissable feature?", category: "Little Things" },
  { q: "What do you hope we're still doing together in 10 years?", category: "Dreams" },
  { q: "What's your favorite inside joke of ours?", category: "Memories" },
  { q: "If I disappeared for a week, what would you miss most?", category: "Deep" },
  { q: "What color reminds you of me and why?", category: "Feelings" },
  { q: "What's a promise you'd want to make to me right now?", category: "Deep" },
  { q: "Finish this: 'Loving you feels like…'", category: "Feelings" },
];